### ISSUE TITLE
use Kansai::Tiny v0.0.1

### ISSUE THREAD

**Issue by nqounet** [kansai-pm/kansai-tiny#1]
## イベントのご案内
- https://manage.doorkeeper.jp/groups/20f04d62ea46c4572f4c02721c/events/29279

**Comment by nqounet** [comment]
@papix 
「Perlで支えるインフラストラクチャー」についてですが、何分くらいお話されますか？

**Comment by tomcha** [comment]
このイベントは、YAPC直前のミートアップ（を主とした）ものって位置付けでいいんですかね？

**Comment by nqounet** [comment]
そうですね。
そういう位置づけですが、YAPC行きたかったけどチケット買えなかった人が気分だけを味わいに来るとかでもいいですね。

**Comment by tomcha** [comment]
了解です。そんな感じのコメント添えて、ツイートします。

**Comment by nqounet** [comment]
ありがとうございます！

**Comment by tomcha** [comment]
リマインダメールか何かで、参加者がサロンの入り口に到着した時にどうしたら良いかと、飲食物持ち込みは禁止をお知らせしといた方がよいですね。
（10時00分丁度まで緑のソファーで待機、とか、到着したらtwitterで＠で連絡 etc）
前回行った時、エレベーターを降りた後にどうしたらよいか迷ったので、案内をしておいた方がよいかと思います。

**Comment by nqounet** [comment]
:+1: なるほど、助かります。

**Comment by sago35** [comment]
直前過ぎて申し訳ないのですが、可能であれば10分枠いただけないでしょうか。
＃急すぎるのもあり、無理なら無理で問題ないですのでばっさりNGとしていただいて良いです

「perlをグラフィカルにデバッグする」というタイトルです。

**Comment by nqounet** [comment]
@sago35  了承いたしました。ありがとうございます。
後で追記しておきます！

**Comment by sago35** [comment]
@nqounet ありがとうございます。
それでは、よろしくお願いします。

**Comment by nqounet** [comment]
本イベントは終了いたしました。
ありがとうございました。
